[definition.vec]
headers = ["../stdme/generic_sources/header/vec_C__PREFIX__.h__TEMPLATE__"]
sources = [
	"../stdme/generic_sources/src/vec_C__PREFIX__.c__TEMPLATE__",
	"../stdme/generic_sources/src/vec_C__PREFIX___functions2.c__TEMPLATE__",
	"../stdme/generic_sources/src/vec_C__PREFIX___functions3.c__TEMPLATE__",
]
replace.C__TYPENAME__ = "type"
replace.C__TYPEHEADER__ = "header_include"
replace.C__PREFIX__ = "prefix"
replace.C__PREFIXUP__ = "prefix"


[definition.hashmap]
headers = ["../stdme/generic_sources/header/hashmap_C__PREFIX__.h__TEMPLATE__"]
sources = [
	"../stdme/generic_sources/src/hashmap_C__PREFIX__.c__TEMPLATE__",
	"../stdme/generic_sources/src/hashmap_C__PREFIX___utils.c__TEMPLATE__",
]
replace.C__VALTYPE__ = "type"
replace.C__KEYTYPE__ = "type"
replace.C__TYPEHEADER__ = "header_include"
replace.C__PREFIX__ = "prefix"
replace.C__PREFIXUP__ = "prefix"


[[create.vec]]
sources_output = "src/vec/"
headers_output = "include/me/vec/"
replace.C__TYPENAME__ = "t_token"
replace.C__TYPEHEADER__ = '#include "lexer/lexer_types.h"'
replace.C__PREFIX__ = "token"
replace.C__PREFIXUP__ = "TOKEN"
